version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/controller"
    schedule:
      interval: "weekly"
    groups:
      go-dependencies:
        patterns:
          - "*"
    open-pull-requests-limit: 5

  - package-ecosystem: "cargo"
    directory: "/agent"
    schedule:
      interval: "weekly"
    groups:
      rust-dependencies:
        patterns:
          - "*"
    open-pull-requests-limit: 5

  - package-ecosystem: "docker"
    directory: "/controller"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/agent"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
