// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: proto/session.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LoginEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SrcIp         uint32                 `protobuf:"varint,1,opt,name=src_ip,json=srcIp,proto3" json:"src_ip,omitempty"`
	DstIp         uint32                 `protobuf:"varint,2,opt,name=dst_ip,json=dstIp,proto3" json:"dst_ip,omitempty"`
	DstPort       uint32                 `protobuf:"varint,3,opt,name=dst_port,json=dstPort,proto3" json:"dst_port,omitempty"`
	Activate      bool                   `protobuf:"varint,4,opt,name=activate,proto3" json:"activate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginEvent) Reset() {
	*x = LoginEvent{}
	mi := &file_proto_session_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginEvent) ProtoMessage() {}

func (x *LoginEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_session_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginEvent.ProtoReflect.Descriptor instead.
func (*LoginEvent) Descriptor() ([]byte, []int) {
	return file_proto_session_proto_rawDescGZIP(), []int{0}
}

func (x *LoginEvent) GetSrcIp() uint32 {
	if x != nil {
		return x.SrcIp
	}
	return 0
}

func (x *LoginEvent) GetDstIp() uint32 {
	if x != nil {
		return x.DstIp
	}
	return 0
}

func (x *LoginEvent) GetDstPort() uint32 {
	if x != nil {
		return x.DstPort
	}
	return 0
}

func (x *LoginEvent) GetActivate() bool {
	if x != nil {
		return x.Activate
	}
	return false
}

type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_proto_session_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_proto_session_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_proto_session_proto_rawDescGZIP(), []int{1}
}

func (x *Ack) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_session_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_session_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_session_proto_rawDescGZIP(), []int{2}
}

type SessionList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sessions      []*Session             `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionList) Reset() {
	*x = SessionList{}
	mi := &file_proto_session_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionList) ProtoMessage() {}

func (x *SessionList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_session_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionList.ProtoReflect.Descriptor instead.
func (*SessionList) Descriptor() ([]byte, []int) {
	return file_proto_session_proto_rawDescGZIP(), []int{3}
}

func (x *SessionList) GetSessions() []*Session {
	if x != nil {
		return x.Sessions
	}
	return nil
}

type Session struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SrcIp         uint32                 `protobuf:"varint,1,opt,name=src_ip,json=srcIp,proto3" json:"src_ip,omitempty"`
	DstIp         uint32                 `protobuf:"varint,2,opt,name=dst_ip,json=dstIp,proto3" json:"dst_ip,omitempty"`
	DstPort       uint32                 `protobuf:"varint,3,opt,name=dst_port,json=dstPort,proto3" json:"dst_port,omitempty"`
	TimeLeft      int32                  `protobuf:"varint,4,opt,name=time_left,json=timeLeft,proto3" json:"time_left,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Session) Reset() {
	*x = Session{}
	mi := &file_proto_session_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Session) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Session) ProtoMessage() {}

func (x *Session) ProtoReflect() protoreflect.Message {
	mi := &file_proto_session_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Session.ProtoReflect.Descriptor instead.
func (*Session) Descriptor() ([]byte, []int) {
	return file_proto_session_proto_rawDescGZIP(), []int{4}
}

func (x *Session) GetSrcIp() uint32 {
	if x != nil {
		return x.SrcIp
	}
	return 0
}

func (x *Session) GetDstIp() uint32 {
	if x != nil {
		return x.DstIp
	}
	return 0
}

func (x *Session) GetDstPort() uint32 {
	if x != nil {
		return x.DstPort
	}
	return 0
}

func (x *Session) GetTimeLeft() int32 {
	if x != nil {
		return x.TimeLeft
	}
	return 0
}

type IpChangeList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IpChanges     []*IpChangeEvent       `protobuf:"bytes,1,rep,name=ip_changes,json=ipChanges,proto3" json:"ip_changes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IpChangeList) Reset() {
	*x = IpChangeList{}
	mi := &file_proto_session_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IpChangeList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IpChangeList) ProtoMessage() {}

func (x *IpChangeList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_session_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IpChangeList.ProtoReflect.Descriptor instead.
func (*IpChangeList) Descriptor() ([]byte, []int) {
	return file_proto_session_proto_rawDescGZIP(), []int{5}
}

func (x *IpChangeList) GetIpChanges() []*IpChangeEvent {
	if x != nil {
		return x.IpChanges
	}
	return nil
}

type IpChangeEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OldIp         uint32                 `protobuf:"varint,1,opt,name=old_ip,json=oldIp,proto3" json:"old_ip,omitempty"`
	NewIp         uint32                 `protobuf:"varint,2,opt,name=new_ip,json=newIp,proto3" json:"new_ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IpChangeEvent) Reset() {
	*x = IpChangeEvent{}
	mi := &file_proto_session_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IpChangeEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IpChangeEvent) ProtoMessage() {}

func (x *IpChangeEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_session_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IpChangeEvent.ProtoReflect.Descriptor instead.
func (*IpChangeEvent) Descriptor() ([]byte, []int) {
	return file_proto_session_proto_rawDescGZIP(), []int{6}
}

func (x *IpChangeEvent) GetOldIp() uint32 {
	if x != nil {
		return x.OldIp
	}
	return 0
}

func (x *IpChangeEvent) GetNewIp() uint32 {
	if x != nil {
		return x.NewIp
	}
	return 0
}

var File_proto_session_proto protoreflect.FileDescriptor

const file_proto_session_proto_rawDesc = "" +
	"\n" +
	"\x13proto/session.proto\x12\asession\"q\n" +
	"\n" +
	"LoginEvent\x12\x15\n" +
	"\x06src_ip\x18\x01 \x01(\rR\x05srcIp\x12\x15\n" +
	"\x06dst_ip\x18\x02 \x01(\rR\x05dstIp\x12\x19\n" +
	"\bdst_port\x18\x03 \x01(\rR\adstPort\x12\x1a\n" +
	"\bactivate\x18\x04 \x01(\bR\bactivate\"\x1f\n" +
	"\x03Ack\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\a\n" +
	"\x05Empty\";\n" +
	"\vSessionList\x12,\n" +
	"\bsessions\x18\x01 \x03(\v2\x10.session.SessionR\bsessions\"o\n" +
	"\aSession\x12\x15\n" +
	"\x06src_ip\x18\x01 \x01(\rR\x05srcIp\x12\x15\n" +
	"\x06dst_ip\x18\x02 \x01(\rR\x05dstIp\x12\x19\n" +
	"\bdst_port\x18\x03 \x01(\rR\adstPort\x12\x1b\n" +
	"\ttime_left\x18\x04 \x01(\x05R\btimeLeft\"E\n" +
	"\fIpChangeList\x125\n" +
	"\n" +
	"ip_changes\x18\x01 \x03(\v2\x16.session.IpChangeEventR\tipChanges\"=\n" +
	"\rIpChangeEvent\x12\x15\n" +
	"\x06old_ip\x18\x01 \x01(\rR\x05oldIp\x12\x15\n" +
	"\x06new_ip\x18\x02 \x01(\rR\x05newIp2\xb0\x01\n" +
	"\x0eSessionManager\x122\n" +
	"\rSubmitSession\x12\x13.session.LoginEvent\x1a\f.session.Ack\x129\n" +
	"\x0fMonitorSessions\x12\x0e.session.Empty\x1a\x14.session.SessionList0\x01\x12/\n" +
	"\bIpChange\x12\x15.session.IpChangeList\x1a\f.session.AckB\x18Z\x16Aegis/controller/protob\x06proto3"

var (
	file_proto_session_proto_rawDescOnce sync.Once
	file_proto_session_proto_rawDescData []byte
)

func file_proto_session_proto_rawDescGZIP() []byte {
	file_proto_session_proto_rawDescOnce.Do(func() {
		file_proto_session_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_session_proto_rawDesc), len(file_proto_session_proto_rawDesc)))
	})
	return file_proto_session_proto_rawDescData
}

var file_proto_session_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_session_proto_goTypes = []any{
	(*LoginEvent)(nil),    // 0: session.LoginEvent
	(*Ack)(nil),           // 1: session.Ack
	(*Empty)(nil),         // 2: session.Empty
	(*SessionList)(nil),   // 3: session.SessionList
	(*Session)(nil),       // 4: session.Session
	(*IpChangeList)(nil),  // 5: session.IpChangeList
	(*IpChangeEvent)(nil), // 6: session.IpChangeEvent
}
var file_proto_session_proto_depIdxs = []int32{
	4, // 0: session.SessionList.sessions:type_name -> session.Session
	6, // 1: session.IpChangeList.ip_changes:type_name -> session.IpChangeEvent
	0, // 2: session.SessionManager.SubmitSession:input_type -> session.LoginEvent
	2, // 3: session.SessionManager.MonitorSessions:input_type -> session.Empty
	5, // 4: session.SessionManager.IpChange:input_type -> session.IpChangeList
	1, // 5: session.SessionManager.SubmitSession:output_type -> session.Ack
	3, // 6: session.SessionManager.MonitorSessions:output_type -> session.SessionList
	1, // 7: session.SessionManager.IpChange:output_type -> session.Ack
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_session_proto_init() }
func file_proto_session_proto_init() {
	if File_proto_session_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_session_proto_rawDesc), len(file_proto_session_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_session_proto_goTypes,
		DependencyIndexes: file_proto_session_proto_depIdxs,
		MessageInfos:      file_proto_session_proto_msgTypes,
	}.Build()
	File_proto_session_proto = out.File
	file_proto_session_proto_goTypes = nil
	file_proto_session_proto_depIdxs = nil
}
