# Build Stage
FROM rust:1.92-slim-bookworm AS builder
WORKDIR /app

# Install dependencies required for eBPF
RUN apt-get update && apt-get install -y \
    clang \
    make \
    libbpf-dev \
    libelf-dev \
    zlib1g-dev \
    pkg-config \
    bpftool \
    && rm -rf /var/lib/apt/lists/*

RUN rustup component add rustfmt

COPY Cargo.toml Cargo.lock ./
COPY src ./src
COPY build.rs ./build.rs

# Generate vmlinux.h
RUN bpftool btf dump file /sys/kernel/btf/vmlinux format c > src/bpf/vmlinux.h

# Build the binary
RUN cargo build --release

# Run Stage
FROM debian:bookworm-slim
WORKDIR /app

RUN apt-get update && apt-get install -y \
    libbpf1 \
    libelf1 \
    zlib1g \
    && rm -rf /var/lib/apt/lists/*

COPY --from=builder /app/target/release/aegis-agent .
CMD ["./aegis-agent", "-i", "eth1"]
